name: Do all the things (master)
on:
  push:
    branches: [ develop ]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      # Runs a single command using the runners shell
    - name: Install dependencies 
      run: npm install
    - name: Build the BOT
      run: npm run build
    - name: SSH into PI
      uses: appleboy/ssh-action@v0.1.4
      with:
        username: pi
        password: ${{secrets.PIPASSWORD}}
        script: |
          whoami
          ls -al
    
